In [1]:
a = [[[1,2],[3,4,5]],[[6,7],[8,9,10]]]
a.shape

AttributeError: 'list' object has no attribute 'shape'

[코드 6-1] 배열 생성

In [ ]:
import numpy as np

#리스트를 생성하고 배열로 변환하기
list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape:',a.shape)
print('a[0]:',a[0])

#2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

a.shape: (4,)
a[0]: 1
b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]


[코드 6-2] 배열 생성 함수

In [ ]:
a = np.zeros(2)
print('a\n', a)

b = np.zeros((2,2))
print('b\n', b)

c = np.ones((2,3))
print('c\n', c)

d = np.full((2,3), 5)
print('d\n', d)

e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[코드 6-2] 배열 생성 함수

In [ ]:
a = np.array([1, 2], dtype=np.float64)
print(a.dtype)

a_i8 = a.astype(np.int8)
print(a_i8.dtype)

float64
int8


[코드 6-4] 배열의 속성 호출

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

print('type(arr):',type(arr))
print('arr.ndim:',arr.ndim)
print('arr.dtype:',arr.dtype)
print('arr.itemsize:',arr.itemsize)
print('arr.size:',arr.size)
print('arr.nbytes:',arr.nbytes)
print('arr.T:\n',arr.T)
print('arr.shape:',arr.shape)

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


[코드 6-5] 배열 모양 변경

In [ ]:
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)

#다차원 배열로 변경하기
a.shape = (2,4)
print('shape\n', a)

#1차원 배열로 변경하기
print('flatten\n', a.flatten( ))

#resize 함수로 모양 변경하기
a.resize((4,2))
print('resize\n', a)

a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


[코드 6-6] 행렬의 행과 열 교차

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

b = a.transpose( )
print('b\n', b)
c = a.T
print('c\n', c)

[코드 6-7] 배열로 마스킹

In [ ]:
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)

data = np.random.randn(4,2)
print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 다르게 나타남

print('\n마스킹된 데이터 출력\n',data[mask])
print('\n마스킹 역전된 데이터 출력\n',data[~mask])

[False  True  True False]

data 출력
 [[ 0.84809383 -0.33254902]
 [-0.10353496 -0.16993669]
 [-0.9191775   0.40646736]
 [-0.74459821  0.41924713]]

마스킹된 데이터 출력
 [[-0.10353496 -0.16993669]
 [-0.9191775   0.40646736]]

마스킹 역전된 데이터 출력
 [[ 0.84809383 -0.33254902]
 [-0.74459821  0.41924713]]


[코드 6-8] 조건식으로 마스킹

In [ ]:
posit = data[data > 0]
print('양수 데이터 출력', '\n',posit)

#다중 조건
over1 = data[1][data[1] > 0]
print('두 번째 행의 양수 데이터 출력','\n',over1)

[코드 6-9] 얕은 복사

In [ ]:
a = np.arange(6)
b = a
print(a)
print(b is a)

b[0] = 10
print(a)

[0 1 2 3 4 5]
True
[10  1  2  3  4  5]


[코드 6-10] 깊은 복사

In [ ]:
a = np.arange(6)
c = a.copy( )

c[0] = 20
print('A: ', a)
print('C: ', c)

A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


[코드 6-11] 배열 정렬

In [ ]:
import numpy as np

a = np.array([3, 2, 5, 1, 4])

print('원본\n',a)
print('정렬 후\n',np.sort(a))


print('원본\n',a)
print('정렬한 인덱스\n',np.argsort(a))

a.sort( )
print('원본\n',a)


원본
 [3 2 5 1 4]
정렬 후
 [1 2 3 4 5]
원본
 [3 2 5 1 4]
정렬한 인덱스
 [3 1 0 4 2]
원본
 [1 2 3 4 5]


## 우수 초콜릿 분석

In [ ]:
#Google Drive Mount
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
import numpy as np
data = np.loadtxt('/content/gdrive/My Drive/Colab Notebooks/실습데이터-파일입출력/chocolate_rating.csv', delimiter=',')
print('차원:', data.ndim)
print('모양:', data.shape)
print('원소 수:', data.size)
print(data)

차원: 2
모양: (1795, 4)
원소 수: 7180
[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]


In [ ]:
ratings_mean = data[:,3].mean( )
print(ratings_mean)

3.185933147632312


In [ ]:
high_level = data[data[:,3] >= 4]
high_id = high_level[:,0].astype(np.int64)
print('우수 초콜릿 수:', high_id.size)
print(high_id)

우수 초콜릿 수: 100
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]


In [ ]:
high_kakao = high_level[:,2]
unique_values, value_counts = np.unique(high_kakao, return_counts=True)
print('카카오 함유량:', unique_values)
print('함유량별 빈도수:', value_counts)

카카오 함유량: [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함유량별 빈도수: [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]


In [ ]:
max_index = np.argmax(value_counts)
print(unique_values[max_index])
print('우수 초콜릿', high_id.size, '가지 중', value_counts[max_index],\
'가지의 카카오 함유량이', unique_values[max_index] * 100, '%입니다.')

0.7
우수 초콜릿 100 가지 중 45 가지의 카카오 함유량이 70.0 %입니다.


# 판다스

[코드 6-12] 리스트로 시리즈 생성

In [ ]:
import pandas as pd
a = pd.Series([1, 2, 3, 4])
print(a)
b = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
print(b)

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64


[코드 6-13] 리스트로 데이터프레임 생성

In [ ]:
list1 = list([['한빛', '남자', '20', '180'],
['한결', '남자', '21', '177'],
['한라', '여자', '20', '160']])
col_names = ['이름', '성별', '나이', '키']
pd.DataFrame(list1, columns=col_names)

이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

[코드 6-14] 딕셔너리로 데이터프레임 생성

In [ ]:
dict1 = {'이름':{0:'한빛',1:'한결',2:'한라'},
        '성별': {0:'남자',1:'남자',2:'여자'},
        '나이': {0:'20',1:'21',2:'20'},
        '키': {0:'180',1:'177',2:'160'}}

pd.DataFrame(dict1)

이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

[코드 6-15] 배열로 데이터프레임 생성

In [ ]:
import numpy as np
arr1 = np.array([['한빛', '남자', '20', '180'],
['한결', '남자', '21', '177'],
['한라', '여자', '20', '160']])
#열 이름 리스트
col_names = ['이름','성별','나이','키']
#데이터프레임 생성하기
pd.DataFrame(arr1, columns=col_names)

이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

[코드 6-16] CSV 파일로 데이터프레임 생성

In [ ]:
list1 = list([['허준호','남자','30','183'],
['이가원','여자','24','162'],
['배규민','남자','23','179'],
['고고림','남자','21','182'],
['이새봄','여자','28','160'],
['이보람','여자','26','163'],
['이루리','여자','24','157'],
['오다현','여자','24','172']])
col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)
df

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

[코드 6-17] 데이터프레임을 CSV 파일로 저장

In [ ]:
#디렉토리에 CSV 파일로 저장하기
df.to_csv('./file.csv', header=True, index=False,
encoding='utf-8') # utf-8 유니코드를 활용한 인코딩 방식
#CSV 파일 읽기
df2 = pd.read_csv('./file.csv', sep=',')
df2

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

[코드 6-18] 모든 열 이름 조회

In [ ]:
df.columns

Index(['이름', '성별', '나이', '키'], dtype='object')

[코드 6-19] 데이터프레임 값 개수와 빈도수 확인

In [ ]:
df.describe( )

이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

[코드 6-20] 데이터프레임의 처음 세 행 검색

In [ ]:
df.head(3)

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

[코드 6-21] 데이터프레임의 마지막 다섯 행 검색

In [ ]:
df.tail( )

이름  성별  나이    키
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

[코드 6-22] 인덱스 기준으로 정렬

In [ ]:
df.sort_index(axis=0).head( )

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

[코드 6-23] 열 기준으로 정렬

In [ ]:
#나이 열과 키 열을 기준으로 행을 정렬하기
df.sort_values(by=['나이', '키'], ascending=False).head( )

이름  성별  나이    키
0  허준호  남자  30  183
4  이새봄  여자  28  160
5  이보람  여자  26  163
7  오다현  여자  24  172
1  이가원  여자  24  162

[코드 6-24] 열 이름으로 데이터 조회

In [ ]:
df[['이름', '키']].head( )

이름    키
0  허준호  183
1  이가원  162
2  배규민  179
3  고고림  182
4  이새봄  160

[코드 6-25] 인덱스로 데이터 조회

In [ ]:
df.iloc[1:4, 0:3]

이름  성별  나이
1  이가원  여자  24
2  배규민  남자  23
3  고고림  남자  21

[코드 6-26] 조건식을 만족하는 데이터 조회(1)

In [ ]:
df[df['키'] > 180].head( )

[코드 6-27] 조건식을 만족하는 데이터 조회(2)

In [ ]:
list1 = list([['허준호', '남자', 30, 183],
['이가원', '여자', 24, 162],
['배규민', '남자', 23, 179],
['고고림', '남자', 21, 182],
['이새봄', '여자', 28, 160],
['이보람', '여자', 26, 163],
['이루리', '여자', 24, 157],
['오다현', '여자', 24, 172]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)
df[df['키'] > 180]

이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

[코드 6-28] 리스트 요소와 일치하는 데이터 조회

In [ ]:
df[df['나이'].isin([21, 23])]

이름  성별  나이    키
2  배규민  남자  23  179
3  고고림  남자  21  182

[코드 6-29] 두 조건식을 동시에 만족하는 데이터 조회

In [ ]:
df[(df['성별'] == '여자') & (df['키'] > 160)]

이름  성별  나이    키
1  이가원  여자  24  162
5  이보람  여자  26  163
7  오다현  여자  24  172

[코드 6-30] 두 조건식 중 하나 이상 만족하는 데이터 조회

In [ ]:
df[(df['나이'] >= 28) | (df['성별'] == '남자')]

이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

[코드 6-31] 특정 문자열을 포함하는 문자열 데이터 조회

In [ ]:
df[df['이름'].str.contains('봄')]

이름  성별  나이    키
4  이새봄  여자  28  160

[코드 6-32] 데이터프레임 통계 확인

In [ ]:
df.describe( )

나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000

[코드 6-33] 인덱스로 조회한 데이터를 수정

In [ ]:
df.loc[4,'키'] = df.loc[4,'키'] + 5
df.loc[[4]]

이름  성별  나이    키
4  이새봄  여자  28  165

코드 6-34] 반복 연산자 사용

In [ ]:
df.loc[1:3,'키'] = ['모름'] * 3
df

NameError: name 'df' is not defined

[코드 6-35] 인덱스 변경(1)

In [ ]:
df.set_index('이름', inplace=True)
df.head(3)

성별  나이    키
이름              
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179

[코드 6-36] 열 생성

In [ ]:
df['보너스'] = df['나이'] * 10000
df.head(3)

성별  나이    키     보너스
이름                      
허준호  남자  30  183  300000
이가원  여자  24  162  240000
배규민  남자  23  179  230000

[코드 6-37] 열 삭제

In [ ]:
df.drop('보너스', axis=1, inplace=True)
df.head(3)

성별  나이    키
이름              
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179

[코드 6-38] 인덱스 변경(2)

In [ ]:
df.reset_index(inplace=True)
df.head(3)

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

[코드 6-39] 데이터 치환

In [ ]:
rep_cond = {'성별':{'남자':1, '여자':0}}
df2 = df.replace(rep_cond)
df2.head(3)

이름  성별  나이    키
0  허준호   1  30  183
1  이가원   0  24  162
2  배규민   1  23  179

[코드 6-40] 데이터프레임의 값 연산

In [ ]:
#성별 평균 키
mean_by_gender = df.groupby(by=['성별'], as_index=False)['키'].mean( )
mean_by_gender.rename(columns={'키':'평균 키'}, inplace=True)

#성별 키의 표준편차
std_by_gender = df.groupby(by=['성별'], as_index=False)['키'].std( )
std_by_gender.rename(columns = {'키':'키의 표준편차'}, inplace=True)

new_df = pd.merge(mean_by_gender, std_by_gender)
new_df

성별        평균 키   키의 표준편차
0  남자  181.333333  2.081666
1  여자  163.800000  5.449771

강의 시간표 분석

1. 열 이름과 시간표 데이터를 리스트로 저장

In [ ]:
col_names = ['과목번호', '과목명', '강의실', '시간수']
list1 = list([['C1', '인공지능개론', 'R1', 3],
['C2', '웃음치료', 'R2', 2],
['C3', '경영학', 'R3', 3],
['C4', '3D디자인', 'R4', 4],
['C5', '스포츠경영', 'R2', 2],
['C6', '예술의 세계', 'R3', 1]])

2. 시간표 데이터를 데이터프레임 객체 df로 변환하여 CSV 파일로 저장.

In [ ]:
import pandas as pd
df = pd.DataFrame(list1, columns=col_names)
df.to_csv('./timetable.csv', header=True, index=False, encoding='utf-8')

3.‘timetable.csv’ 파일을 데이터프레임 객체 df2로 읽고, 열 이름이 ‘교수’인 열을추가. 값으로 ‘김예희’, ‘오정현’, ‘인세훈’, ‘이새봄’, ‘배유진’, ‘이가원’을 저장

In [ ]:
df2 = pd.read_csv('./timetable.csv', sep=',')
df2['교수'] = ['김예희', '오정현', '인세훈', '이새봄', '배유진', '이가원']
df.to_csv('./timetable.csv', header=True, index=False, encoding='utf-8')
df2

과목번호     과목명 강의실  시간수   교수
0   C1  인공지능개론  R1    3  김예희
1   C2    웃음치료  R2    2  오정현
2   C3     경영학  R3    3  인세훈
3   C4   3D디자인  R4    4  이새봄
4   C5   스포츠경영  R2    2  배유진
5   C6  예술의 세계  R3    1  이가원

4. 강의실을 기준으로 그룹화하여 max() 함수로 최대 시간 수를 구하기.

In [ ]:
max_hour = df2.groupby(by=['강의실'],
as_index=False)['시간수'].max( )
max_hour

강의실  시간수
0  R1    3
1  R2    2
2  R3    3
3  R4    4